import Head from "next/head";
import Image from "next/image";
import NextLink from 'next/link';
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";
import DashboardHero from "../components/hero";
import { Box, Heading, Container, Text, Grid, GridItem, Checkbox, Button, Link } from '@chakra-ui/react';

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Dashboard(props) {
  const router = useRouter();
  const logout = useLogout();
  return (
    <Container maxW="container.md">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props.user.username} />



      <DashboardHero user={props.user} />

      

      <Box as="footer" mt={8} textAlign="center">
        <Link as={NextLink}
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          isExternal
        >
          Powered by{" "}
          <Image 
            src="/vercel.svg" 
            alt="Vercel Logo" 
            width={72} 
            height={16} 
            priority 
          />
        </Link>
      </Box>
    </Container>
  );
}