import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";
import { Box, Button, Code, Container, Flex, Heading, Text, VStack } from "@chakra-ui/react";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  const router = useRouter();
  const logout = useLogout();


  return (
    <Container maxW="container.md">
      <Head>
        <title>Amimovie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <Flex direction="column" align="center" justify="center" minH="100vh" py={8}>
        <Heading as="h1" size="2xl" mb={8}>
          Welcome to amimovie
        </Heading>

        <Heading as="h2" size="1xl" mb={8}>
          Login or create an account to browse movies you may like and save them in your dashboard.
        </Heading>

        <Text fontSize="lg" mb={4}>
          Current Location: <code>{router.asPath}</code>
          <br />
          Status: <Code>{!props.isLoggedIn ? "Not" : ""} Logged In</Code>
        </Text>

        <VStack spacing={4}>
          {props.isLoggedIn ? (
            <>
              <Link href="/dashboard">
              <Button colorScheme="teal" size="lg">
                  Dashboard
                </Button>
              </Link>
              <Button onClick={logout} colorScheme="red" size="lg">
                Logout
              </Button>
            </>
          ) : (
            <>
              <Link href="/login">
              <Button colorScheme="teal" size="lg">
                  Login
                </Button>
              </Link>

              <Link href="/signup">
              <Button colorScheme="teal" size="lg">
                  Create Account
                </Button>
              </Link>
            </>
          )}
        </VStack>
      </Flex>

      <Box as="footer" mt={8} textAlign="center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </Box>
    </Container>
  );
}
