import Head from "next/head";
import Image from "next/image";
import NextLink from 'next/link';
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";
import { Box, Code, Container, Flex, Heading, Text, VStack, Link, LinkBox } from "@chakra-ui/react";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  const router = useRouter();
  const logout = useLogout();
  const isCreatingAccount = router.pathname === '/signup';

  return (
    
    <Container maxW="container.md">
      <Head>
        <title>Amimovie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Render the Header only if logged in or creating an account */}
      {(props.isLoggedIn || isCreatingAccount) && (
        <Box as="header" w="100%" maxW="container.lg" mx="auto" p={4}>
          <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />
        </Box>
      )}

      <Flex direction="column" align="center" justify="center" minH="100vh" py={8}>
        <Heading as="h1" size="2xl" mb={8}>
          Welcome to <Text as="span" color="orange.300">amimovie</Text>
        </Heading>

        <Box textAlign="center" px={4} py={8}>
          <Text
            fontSize={{ base: "md", sm: "lg", md: "xl", lg: "2xl" }}
            mb={8}
            mx="auto"
          >
            Save 3 of your favorite genres to get customized movie recommendations.
          </Text>
        </Box>

        <Text fontSize="m" mb={4}>
          You are <Code>{!props.isLoggedIn ? "Not" : ""} Logged In</Code>
        </Text>

        <VStack spacing={4} align="stretch">
          {props.isLoggedIn ? (
            <>
              <Box
                onClick={() => router.push('/dashboard')}
                cursor="pointer"
                p={5}
                shadow="md"
                borderWidth="1px"
                _hover={{ bg: "gray.100" }}
              >
                <Heading as="h2" size="md">
                  Dashboard &rarr;
                </Heading>
                <Text>Click to select favorite genres.</Text>
              </Box>

              <Box
                onClick={logout}
                cursor="pointer"
                p={5}
                shadow="md"
                borderWidth="1px"
                _hover={{ bg: "gray.100" }}
              >
                <Heading as="h2" size="md">
                  Logout &rarr;
                </Heading>
                <Text>Click here to log out.</Text>
              </Box>
            </>
          ) : (
            <>
              <Link as={NextLink} href="/login" _hover={{ textDecoration: "none" }}>
                <Box p={5} shadow="md" borderWidth="1px">
                  <Heading size="md">Login <Text as="span" color="orange.300">&rarr;</Text></Heading>
                  <Text>Welcome back!</Text>
                </Box>
              </Link>

              <Link as={NextLink} href="/signup" _hover={{ textDecoration: "none" }}>
                <Box p={5} shadow="md" borderWidth="1px">
                  <Heading size="md">Create Account <Text as="span" color="orange.300">&rarr;</Text></Heading>
                  <Text>To get movie recommendations</Text>
                </Box>
              </Link>
            </>
          )}
        </VStack>
      </Flex>

      <Box as="footer" mt={8} textAlign="center">
        <Link as={NextLink}
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          isExternal
        >
          Powered by{" "}
          <Image 
            src="/vercel.svg" 
            alt="Vercel Logo" 
            width={72} 
            height={16} 
            priority 
          />
        </Link>
      </Box>
    </Container>
  );
}