import Head from "next/head";
import Image from "next/image";
import NextLink from 'next/link';
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { Link, Box, Heading, Container, Text, Code, Flex, FormLabel, FormControl, Button, Input } from '@chakra-ui/react';

export default function Signup(props) {
  const router = useRouter();
  const [
    { username, password, "confirm-password": confirmPassword },
    setForm,
  ] = useState({
    username: "",
    password: "",
    "confirm-password": "",
  });
  const [error, setError] = useState("");

  function handleChange(e) {
    setForm({
      username,
      password,
      "confirm-password": confirmPassword,
      ...{ [e.target.name]: e.target.value.trim() },
    });
  }
  async function handleCreateAccount(e) {
    e.preventDefault();
    if (!username) return setError("Must include username");
    if (password !== confirmPassword) return setError("Passwords must Match");

    try {
      const res = await fetch("/api/auth/signup", {
        method: "POST",
        headers: {
          "content-type": "application/json",
        },
        body: JSON.stringify({ username, password }),
      });
      if (res.status === 200) return router.push("/dashboard");
      const { error: message } = await res.json();
      setError(message);
    } catch (err) {
      console.log(err);
    }
  }
  return (
    <Container maxW="container.md">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction="column" align="center" justify="center" minH="100vh" py={8}>
        <Heading as="h1" size="2xl" mb={8}>
          Welcome to the{" "}
          <Text as="span" color="orange.300">
            amimovie
          </Text>
          <Text>
            Signup page!
          </Text>
        </Heading>

        <Text fontSize="md" mb={4}>
          You are <Code>{!props.isLoggedIn ? "Not" : ""} Logged In</Code>
        </Text>

        <Box
          as="form"
          onSubmit={handleCreateAccount}
          width="100%"
          maxW="md"
          p={8}
          borderWidth={1}
          borderRadius="lg"
          boxShadow="lg"
          bg="white"
        >
          <FormControl id="username" mb={4}>
            <FormLabel>Username</FormLabel>
            <Input
              type="text"
              name="username"
              value={username}
              onChange={handleChange}
              required
              bg="gray.50"
              borderColor="gray.300"
              _placeholder={{ color: "gray.500" }}
            />
          </FormControl>

          <FormControl id="password" mb={4}>
            <FormLabel>Password</FormLabel>
            <Input
              type="password"
              name="password"
              value={password}
              onChange={handleChange}
              required
              bg="gray.50"
              borderColor="gray.300"
              _placeholder={{ color: "gray.500" }}
            />
          </FormControl>

          <FormControl id="confirm-password" mb={4}>
            <FormLabel>Confirm Password</FormLabel>
            <Input
              type="password"
              name="confirm-password"
              value={confirmPassword}
              onChange={handleChange}
              required
              bg="gray.50"
              borderColor="gray.300"
              _placeholder={{ color: "gray.500" }}
            />
          </FormControl>

          <Button
            type="submit"
            color="white"
            bg="orange.300"
            width="full"
            mb={4}
            _hover={{ bg: "orange.400" }}
          >
            Submit
          </Button>

          {error && <Text color="red.500">{error}</Text>}
        </Box>

        <Link as={NextLink} href="/login" mt={4}>
          <Text color="teal.500" mt={4}>
            Login instead?
          </Text>
        </Link>

        <Box as="footer" mt={8} textAlign="center">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </Box>
      </Flex>
    </Container>
  );
}